name: GitHub Actions
run-name: TODO ðŸš€
on: [push]
jobs:
  TODO_Name:
    runs-on: ubuntu-latest
    steps:
      # import
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # test build
      - run: bun install
      # format
      - run: bun run format
      # TODO: test
      # build
      - run: bun run build
